version: 0.0
os: linux
files:
  - source: AngularAppTest
    destination: /var/tmp
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  # remove files or install dependencies    
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    # - location: scripts/write_codedeploy_config.sh
    - location: scripts/start_server
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/basic_health_check.sh
      runas: root
